# Pipeline de CI/CD para deploy automático no IIS
# Executa após merge na branch main/master

stages:
  - build
  - deploy

variables:
  # Configurações do projeto
  PROJECT_NAME: "sgcr_novo"
  IIS_SITE_NAME: "SGCR_NEW"
  IIS_APP_POOL: "SGCR_NEW"
  PHP_VERSION: "8.2"

# Cache para otimizar builds
cache:
  paths:
    - vendor/
    - node_modules/

# =============================
# JOB DE BUILD
# =============================
build:
  stage: build
  tags:
    - dev
    - iis
    - windows
  script:
    - echo "🚀 Iniciando build da aplicação..."
    - composer install --no-dev --optimize-autoloader
    # Usa o .env do servidor, então aqui não criamos .env
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan view:clear
    - echo "✅ Build concluída com sucesso!"
  artifacts:
    paths:
      - app/
      - bootstrap/
      - config/
      - database/
      - lang/
      - public/
      - resources/
      - routes/
      - storage/
      - artisan
    exclude:
      - "/node_modules"
      - "/.git"
      - "/tests"
      - "/*.log"
      - "/storage/logs"
      - "/storage/framework/cache"
      - ".env"             # Garante que nunca vai junto
      - ".env.example"
    expire_in: 1 hour
  only:
    - main
    - master
  except:
    - tags

# =============================
# JOB DE DEPLOY
# =============================
deploy:
  stage: deploy
  tags:
    - dev
    - iis
    - windows
  script:
    - echo "🚀 Iniciando deploy no IIS..."
    # Configurar credenciais de rede usando variáveis do GitLab
    - |
      cmdkey /add:${DEPLOY_SERVER} /user:${DEPLOY_USERNAME} /pass:${DEPLOY_PASSWORD}
      Write-Host "Credenciais de rede configuradas"
    # Criar diretório de backup se não existir
    - if (!(Test-Path "${BACKUP_DIR}")) { New-Item -ItemType Directory -Path "${BACKUP_DIR}" -Force }
    # Backup simples (sem .env)
    - |
      if (Test-Path "${DEPLOY_DIR}") {
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $backupPath = "${BACKUP_DIR}\\backup_${timestamp}"
        Write-Host "Criando backup em: $backupPath"
        New-Item -ItemType Directory -Path "$backupPath" -Force
        robocopy "${DEPLOY_DIR}" "$backupPath" /E /XD "vendor" "node_modules" "tests" ".git" /XF "*.log" ".env" ".env.example"
        Write-Host "Backup concluído com sucesso!"
      }
    # Deploy incremental (sem .env)
    - Write-Host "Copiando arquivos da aplicação..."
    - |
      try {
        robocopy "${SOURCE_DIR}" "${DEPLOY_DIR}" /MIR /IS /IT /XD "node_modules" "tests" ".git" "vendor" "storage" "bootstrap/cache" /XF "*.log" ".env" ".env.example" /R:3 /W:10
        Write-Host "Robocopy aplicação concluído (código: $LASTEXITCODE)"
      } catch {
        Write-Host "Robocopy aplicação concluído (com erro, mas continuando...)"
      }
    # Copiar dependências
    - Write-Host "Copiando dependências..."
    - |
      try {
        robocopy "${SOURCE_DIR}\\vendor" "${DEPLOY_DIR}\\vendor" /E /R:3 /W:10
        Write-Host "Robocopy vendor concluído (código: $LASTEXITCODE)"
      } catch {
        Write-Host "Robocopy vendor concluído (com erro, mas continuando...)"
      }
    - Write-Host "✅ Deploy concluído com sucesso!"
    # Limpar backups antigos
    - Write-Host "Limpando backups antigos..."
    - |
      $backups = Get-ChildItem "${BACKUP_DIR}" -Directory | Sort-Object CreationTime -Descending | Select-Object -Skip 5
      foreach ($backup in $backups) {
        Remove-Item $backup.FullName -Recurse -Force
        Write-Host "Backup removido: $($backup.Name)"
      }
  environment:
    name: development
    url: http://des-sgcr_novo.ipen.br
  only:
    - main
    - master
  except:
    - tags
  allow_failure: false